package com.task.model

import scodec._
import codecs._
import FieldCodecs._
import scodec.bits.ByteVector

sealed trait Request

/*

Parameter	        Offset,         Length in bytes	        Value	                            Description
auth_key_id	      0,              8	                      0	                                Since message is in plain text
message_id	      8,              8	                      51e57ac42770964a	                Exact unixtime * 2^32
message_length	  16,             4	                      20	                              Message body length
%(req_pq)	        20,             4	                      60469778	                        req_pq constructor number from TL schema
nonce	            24,             16	                    3E0549828CCA27E966B301A48FECE2FC	Random number
 */
final case class RequestPQ(authKeyId: Long, messageId: Long, messageLength: Int, reqPQ: Int, nonce: BigInt) extends Request

object RequestPQ {
  val codec: Codec[RequestPQ] = (int64L :: int64L :: int32L :: int32L :: nonceCodec).as[RequestPQ]
}

/*
Parameter	              Offset,         Length in bytes	        Value	                            Description
auth_key_id	            0,              8	                      0	                                Since message is in plain text
message_id	            8,              8	                      51e57ac917717a27	                Exact unixtime * 2^32
message_length	        16,             4	                      320	                              Message body length
%(req_DH_params)	      20,             4	                      d712e4be	                        req_DH_params constructor number from TL schema
nonce	                  24,             16	                    3E0549828CCA27E966B301A48FECE2FC	Value generated by client in Step 1
server_nonce	          40,             16	                    A5CF4D33F4A11EA877BA4AA573907330	Value received from server in Step 2
p	                      56,             8	                      494C553B	                        First prime cofactor: single-byte prefix denoting length, 4-byte string, and three bytes of padding
q	                      64,             8	                      53911073	                        Second prime cofactor: single-byte prefix denoting length, 4-byte string, and three bytes of padding
public_key_fingerprint	72,             8	                      c3b42b026ce86b21	                Fingerprint of public key used
encrypted_data	        80,             260	
 */
final case class RequestDHParams(
  authKeyId: Long,
  messageId: Long,
  messageLength: Int,
  reqDHParams: Int,
  nonce: BigInt, // from requestPQ
  serverNonce: BigInt, // from responsePQ
  p: Int,
  q: Int,
  publicKeyFingerprint: ByteVector,
  encryptedData: ByteVector // todo: should be decrypted
) extends Request

object RequestDHParams {
  val codec: Codec[RequestDHParams] =
    (int64L :: int64L :: int32L :: int32L :: nonceCodec :: serverNonceCodec :: pCodec :: qCodec :: publicKeyCodec :: encryptedDataCodec)
      .as[RequestDHParams]
}

/*
Parameter	        Offset,         Length in bytes	        Value	                            Description
%(p_q_inner_data)	0,              4	                      83c95aec	                        p_q_inner_data constructor number from TL schema
pq	              4,              12	                    17ED48941A08F981	                Single-byte prefix denoting length, 8-byte string, and three bytes of padding
p	                16,             8	                      494C553B	                        First prime cofactor: single-byte prefix denoting length, 4-byte string, and three bytes of padding
q	                24,             8	                      53911073	                        Second prime cofactor: single-byte prefix denoting length, 4-byte string, and three bytes of padding
nonce	            32,             16	                    3E0549828CCA27E966B301A48FECE2FC	Value generated by client in Step 1
server_nonce	    48,             16	                    A5CF4D33F4A11EA877BA4AA573907330	Value received from server in Step 2
new_nonce	        64,             32	                    311C85DB234AA2640AFC4A76A735CF5B  Client-generated random number
                                                          1F0FD68BD17FA181E1229AD867CC024D
 */
final case class InnerData(
  pqInnerData: Int,
  pq: BigInt,
  p: Int,
  q: Int,
  nonce: BigInt,
  serverNonce: BigInt,
  newNonce: BigInt
)

object InnerData {
  val codec: Codec[InnerData] =
    (int32L :: pqCodec :: pCodec :: qCodec :: nonceCodec :: serverNonceCodec :: newNonceCodec).as[InnerData]
}
